# Generated by Django 3.2.9 on 2021-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('decrypted', models.TextField()),
            ],
        ),
    ]
